spring:
    application.name: yson-converter
    main.banner-mode: off

logging:
    level:
        root: INFO
        org.springframework: INFO
    file:
        path: ./logs
    logback:
        rollingpolicy:
            max-file-size: 10MB
            total-size-cap: 100MB
            max-history: 5
